### ISSUE TITLE
translation to anyOf and oneOf has been inverted throughout the conversion process

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#245]
According to the [JSON schema spec](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.5.4)

## AnyOf

> An instance validates successfully against this keyword if it
   validates successfully against *at least one schema* defined by this
   keyword's value.

## OneOf

> An instance validates successfully against this keyword if it
   validates successfully against *exactly one schema* defined by this
   keyword's value.

There are a number of places where the conversion library is using anyOf when it should be using instead oneOf, and it seems the confusion originates from the early days of the library, as [this comment](https://github.com/microsoft/OpenAPI.NET.OData/blob/bdf4241355caba36c7180dc4fd46064a870a161c/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs#L143) would indicate.

If we take the example of OData double to illustrate this issue, the library currently produces this.

```yaml
                zoom:
                  anyOf:
                    - type: number
                    - type: string
                    - enum:
                        - '-INF'
                        - INF
                        - NaN
                  format: double
                  nullable: true
```

Which could be translated to a human sentence to "any instance that is a number (rational) or a string or -INF or INF or NaN is a double".
But the missing details here is that we're using "or" and not "xor" (exclusive or).
Semantically speaking, the value will (and should) never be a number AND -INF for example.

I believe the right *human* sentence should be "any instance that is a number (rational) or a string or -INF or INF or NaN to exactly one of these options is a double". Which would result in the following.

```yaml
                zoom:
                  oneOf:
                    - type: number
                    - type: string
                    - enum:
                        - '-INF'
                        - INF
                        - NaN
                  format: double
                  nullable: true
```

This is even more evident with the geometric data structures where a geometric information can be a point or a line but not both (mathematically speaking, a line is defined a continuous set of points).
https://github.com/microsoft/OpenAPI.NET.OData/blob/bdf4241355caba36c7180dc4fd46064a870a161c/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSpatialTypeSchemaGenerator.cs#L217-L225

# TODO

- [x] update geometric points (link above) to oneOf
- [x] update [decimal](https://github.com/microsoft/OpenAPI.NET.OData/blob/bdf4241355caba36c7180dc4fd46064a870a161c/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs#L169) and down to oneOf
- [x] update unit and integration tests
- [x] (optional) make components for Edm double, decimal and single
